### ISSUE TITLE
unused deallocate in Allocator

### ISSUE THREAD

**Issue by gpzlx1** [owensgroup/BGHT#21]
Great work. 

Now I try to build this repo with my allocator. However, the BGHT only call `cuda_deleter` to release the memory rather than `deallocate` in my custom allocator which causes the exception.

Hope to solve this bug in the future. : )

**Comment by maawad** [comment]
Thanks @gpzlx1 for the bug report. I fixed the issue you reported in #22. Feel free to reopen the issue if you are you still having problems with the custom allocators.
