### ISSUE TITLE
Fused the reason why key_not_found when cur_bucket.compute_load(sentinel_pair) < bucket_size ?

### ISSUE THREAD

**Issue by alphaRGB** [owensgroup/BGHT#6]
Hello, I have some questions about the GPU kernel of **bcht**, It is great if you explain these questions when you are free,  thank you in advance.

In the below function:

```
template <class Key,
          class T,
          class Hash,
          class KeyEqual,
          cuda::thread_scope Scope,
          class Allocator,
          int B>
template <typename tile_type>
__device__ bght::bcht<Key, T, Hash, KeyEqual, Scope, Allocator, B>::mapped_type
bght::bcht<Key, T, Hash, KeyEqual, Scope, Allocator, B>::find(key_type const& key,
                                                              tile_type const& tile) {
  const int num_hfs = 3;
  auto bucket_id = hf0_(key) % num_buckets_;
  value_type sentinel_pair{sentinel_key_, sentinel_value_};
  using bucket_type = detail::bucket<atomic_pair_type, value_type, tile_type>;
  for (int hf = 0; hf < num_hfs; hf++) {
    bucket_type cur_bucket(&d_table_[bucket_id * bucket_size], tile);
    cur_bucket.load(cuda::memory_order_relaxed);
    INCREMENT_PROBES_IN_TILE
    int key_location = cur_bucket.find_key_location(key, key_equal{});
    if (key_location != -1) {
      auto found_value = cur_bucket.get_value_from_lane(key_location);
      return found_value;
    } else if (cur_bucket.compute_load(sentinel_pair) < bucket_size) {
      return sentinel_value_;
    } else {
      bucket_id = hf == 0 ? hf1_(key) % num_buckets_ : hf2_(key) % num_buckets_;
    }
  }

  return sentinel_value_;
}

```
## Q1

Question about the condiction:  `cur_bucket.compute_load(sentinel_pair) < bucket_size`   https://github.com/owensgroup/BGHT/blob/fac9d91db84e2c87c69a280086a43e66cf5d9639/include/detail/bcht_impl.cuh#L265 ,  could you please help me explain it ?

Here is my understand of this function:  find the count of non-empty slots of the bucket,  is it right ?  In my option, ret = compute_load() always little than or equal to **bucket_size**
```
  int compute_load(const pair_type& sentinel) {
    auto load_bitmap = tile_.ballot(lane_pair_.first != sentinel.first);
    int load = __popc(load_bitmap);
    return load;
  }
```

---

## Q2
https://github.com/owensgroup/BGHT/blob/fac9d91db84e2c87c69a280086a43e66cf5d9639/include/detail/bcht_impl.cuh#L263
Why using  `tile_.shfl()`  to broadcast the found value to others threads of the tile ?  why not return `lane_pair.second` directly ?
```
  typename pair_type::second_type get_value_from_lane(int location) {
    return tile_.shfl(lane_pair_.second, location);
  }
```

**Comment by maawad** [comment]
Hi @alphaRGB, 
For the first question: If the bucket's load is less than the bucket size (i.e., the bucket contains at least one empty spot) and the key was not found in the bucket (first part of the if statement), then the key doesn't exist in the hash table. We can do this early termination since when we insert a key, we use the three hash functions in order.

For your second question: The insertion and find algorithms are cooperative (i.e., requiring a group of threads to perform it). In insertion, we expect all threads inside the group to pass the same key, and similarly, when we find a result, all threads will return the same result.

**Comment by alphaRGB** [comment]
> Hi @alphaRGB, For the first question: If the bucket's load is less than the bucket size (i.e., the bucket contains at least one empty spot) and the key was not found in the bucket (first part of the if statement), then the key doesn't exist in the hash table. We can do this early termination since when we insert a key, we use the three hash functions in order.
> 
> For your second question: The insertion and find algorithms are cooperative (i.e., requiring a group of threads to perform it). In insertion, we expect all threads inside the group to pass the same key, and similarly, when we find a result, all threads will return the same result.

Thank you very much, I have understand what you explain of both 2 questions.  I mainly focused hash_find before, I'll read hash_insert also.
