### ISSUE TITLE
HOW to build BGHT on AMD GPU?

### ISSUE THREAD

**Issue by xianwujie** [owensgroup/BGHT#9]
Hello. could you help me?
I want to build this project on AMD GPU. is this possible?

**Comment by maawad** [comment]
Hi @xianwujie, our code targets [Volta or later microarchitecture NIVIDA GPUs](https://github.com/owensgroup/BGHT#requirements). I'd suggest looking at tools like [HIPIFY](https://github.com/ROCm-Developer-Tools/HIPIFY) that translate CUDA source code into HIP C++, which runs on AMD GPUs. I haven't used HIPIFY before, so I'm not sure if all the CUDA/hardware features we use are supported or not.

If you try to translate our code to something that runs on AMD hardware and have questions about our implementations, let us know, and we will be happy to answer your questions.

**Comment by xianwujie** [comment]
Hi @maawad ,Thanks for your reply, I will I convert the code with HIPIFY as per your suggestion.
